var expect = require('chai').expect;
var {gensymff, inc} = require('..');

describe('gensymff', function () {
  it('is a function', function () {
    expect(gensymff).to.be.a('function');
  });
  it('returns a function', function () {
    expect(gensymff()).to.be.a('function');
  });
  it('returns a gensymf-type function that emits unique strings starting with the passed argument, with values generated by the unary function, starting from the seed', function () {
    var gensymf = gensymff(inc, 1);
    var genNC = gensymf('NC');
    expect(genNC()).to.equal('NC2');
    expect(genNC()).to.equal('NC3');
    expect(genNC()).to.equal('NC4');
    expect(genNC()).to.equal('NC5');
  });
});